// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Domain
{
    public partial class Detail
    {
        public Detail()
        {
            WorkshopDetails = new HashSet<WorkshopDetail>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string MarkDetail { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal Massa { get; set; }

        [InverseProperty(nameof(WorkshopDetail.Detail))]
        public virtual ICollection<WorkshopDetail> WorkshopDetails { get; set; }
    }
}