// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Domain
{
    public partial class WorkshopDetail
    {
        [Key]
        public int DetailId { get; set; }
        [Key]
        public int OperationNumber { get; set; }
        public int WorkshopNumber { get; set; }
        public int DayForCreate { get; set; }
        [Column(TypeName = "numeric(18, 3)")]
        public decimal PriceOperation { get; set; }

        [ForeignKey(nameof(DetailId))]
        [InverseProperty("WorkshopDetails")]
        public virtual Detail Detail { get; set; }
        [ForeignKey(nameof(WorkshopNumber))]
        [InverseProperty(nameof(Workshop.WorkshopDetails))]
        public virtual Workshop WorkshopNumberNavigation { get; set; }
    }
}