// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Domain
{
    [Table("Workshop")]
    public partial class Workshop
    {
        public Workshop()
        {
            WorkshopDetails = new HashSet<WorkshopDetail>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string WorkshopName { get; set; }
        [Required]
        public string DirectorName { get; set; }
        [Required]
        public string MiddleName { get; set; }
        [Required]
        public string LastName { get; set; }

        [InverseProperty(nameof(WorkshopDetail.WorkshopNumberNavigation))]
        public virtual ICollection<WorkshopDetail> WorkshopDetails { get; set; }
    }
}